# Generated by Django 4.0.5 on 2022-06-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover_image',
            field=models.CharField(default='', max_length=30),
        ),
    ]
