# Generated by Django 4.0.5 on 2022-06-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_movie_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover_image',
            field=models.CharField(default='', max_length=250),
        ),
    ]
