# Generated by Django 4.0.5 on 2022-07-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_movie_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
